# Generated by Django 3.0.4 on 2020-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(choices=[('CALS', 'Collge of Agriculture and Life Sciences'), ('COE', 'College of Engineering')], max_length=4)),
                ('graduation_date', models.IntegerField()),
            ],
        ),
    ]
