# Generated by Django 3.0.4 on 2020-03-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnus',
            new_name='Alumni',
        ),
    ]
