# Generated by Django 3.0.3 on 2020-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_auto_20200313_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
