# Generated by Django 3.0.3 on 2020-03-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0005_auto_20200313_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
