# Generated by Django 3.0.3 on 2020-04-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0008_auto_20200411_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='joined_year',
            field=models.IntegerField(default=2018),
        ),
    ]
