# Generated by Django 3.0.3 on 2020-04-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0009_auto_20200424_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
