# Generated by Django 3.0.3 on 2020-04-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0010_auto_20200428_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
